[package]
name = "uefi-test"
version = "0.1.0"
edition = "2024"

[dependencies]
embedded-graphics = "0.8.1"
uefi-graphics2 = "0.5.0"

[dependencies.uefi]
version = "0.35.0"
features = ["alloc", "panic_handler", "global_allocator", "logger"]
